export const BOOK_LIST = 'Book List'
export const BOOK_DETAIL = 'Book Details'
export const CREATE_BOOK = 'Add New Book'
export const LOGIN = 'Login'
export const REGISTER = 'Register'
export const HOME_NAVIGATOR = 'Book List'